package:
  name: condaPackageTest
  version: "0.1"

source:
  git_rev: v0.1
  git_url: https://github.com/carlosloslas/condaPakageTest.git

requirements:
  build:
    - python
    script: python setup.py install
  run:
    - python
  test:
    imports:
      - python
about:
  home: https://github.com/carlosloslas/condaPakageTest
  license: MIT
  license_file: LICENSE
